name: Update meta-repository

on:
  schedule:
    - cron: "15 */1 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id}}
  cancel-in-progress: true

jobs:
  update-readme:
    name: Update README via template editing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - run: |
          uv sync

      - name: Perform edit and replacements
        run: |
          uv run python readme.py

      - name: Conditionally revert previous commit
        run: |
          if [[ "$(git show -s --format='%ae' HEAD)" == *"github-actions"* ]]; then
            git reset --hard HEAD^;
          fi

      - name: Commit and push changes
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add README.md
          git commit -m "Autogenerated commit for updated README on $(date +%Y-%m-%d_%H-%M)"
          git push --force